In [1]:
import numpy as np
from heeps.util.multiCPU import multiCPU

In [2]:
a = 1
b = 2
c = 7
frame1 = np.ones((5,5))
frame1[3,0] *= 2
cube = np.float32(np.vstack(([frame1], [frame1*2], [frame1*3])))
print(cube)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [2. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]
  [4. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]]

 [[3. 3. 3. 3. 3.]
  [3. 3. 3. 3. 3.]
  [3. 3. 3. 3. 3.]
  [6. 3. 3. 3. 3.]
  [3. 3. 3. 3. 3.]]]


In [3]:
def calc_zero(A):
    return A.T[0,1:].T
def calc_one(a, b, A, B, C, c=0):
    D = (a*A + b*B + c*C).T
    return D[0,1:].T
def calc_two(a, b, A, B, C, c=0):
    D = calc_one(a, b, A, B, C, c)
    return D, -D

## case zero

In [4]:
frame0 = calc_zero(cube[0])
print('len = %s'%len(frame0))
print('type = %s'%type(frame0))
print('array shape =', np.array(frame0).shape)
frame0

len = 4
type = <class 'numpy.ndarray'>
array shape = (4,)


array([1., 1., 2., 1.], dtype=float32)

In [5]:
cube0 = calc_zero(cube)
print('len = %s'%len(cube0))
print('type = %s'%type(cube0))
print('array shape =', np.array(cube0).shape)
cube0

len = 3
type = <class 'numpy.ndarray'>
array shape = (3, 4)


array([[1., 1., 2., 1.],
       [2., 2., 4., 2.],
       [3., 3., 6., 3.]], dtype=float32)

In [6]:
mult0 = multiCPU(calc_zero, posvars=[cube])
print('len = %s'%len(mult0))
print('type = %s'%type(mult0))
print('array shape =', np.array(mult0).shape)
mult0

   2021-05-10 17:58:38, using 12 cores
   2021-05-10 17:58:38, completed in 0.17 seconds
len = 3
type = <class 'numpy.ndarray'>
array shape = (3, 4)


array([[1., 1., 2., 1.],
       [2., 2., 4., 2.],
       [3., 3., 6., 3.]], dtype=float32)

## case one

In [7]:
frame1 = calc_one(a, b, cube[0], cube[0], cube[0], c)
print('len = %s'%len(frame1))
print('type = %s'%type(frame1))
print('array shape =', np.array(frame1).shape)
frame1

len = 4
type = <class 'numpy.ndarray'>
array shape = (4,)


array([10., 10., 20., 10.], dtype=float32)

In [8]:
cube1 = calc_one(a, b, cube, cube, cube, c)
print('len = %s'%len(cube1))
print('type = %s'%type(cube1))
print('array shape =', np.array(cube1).shape)
cube1

len = 3
type = <class 'numpy.ndarray'>
array shape = (3, 4)


array([[10., 10., 20., 10.],
       [20., 20., 40., 20.],
       [30., 30., 60., 30.]], dtype=float32)

In [9]:
mult1 = multiCPU(calc_one, posargs=[a,b], posvars=[cube,cube,cube], kwargs=dict(c=c))
print('len = %s'%len(mult1))
print('type = %s'%type(mult1))
print('array shape =', np.array(mult1).shape)
mult1

   2021-05-10 17:58:38, using 12 cores
   2021-05-10 17:58:38, completed in 0.18 seconds
len = 3
type = <class 'numpy.ndarray'>
array shape = (3, 4)


array([[10., 10., 20., 10.],
       [20., 20., 40., 20.],
       [30., 30., 60., 30.]], dtype=float32)

In [10]:
mult1 = multiCPU(calc_one, posargs=[a,b], posvars=[cube,cube,cube], kwargs=dict(c=c), cpu_count=1)
print('len = %s'%len(mult1))
print('type = %s'%type(mult1))
print('array shape =', np.array(mult1).shape)
mult1

   2021-05-10 17:58:38, using 1 core
   2021-05-10 17:58:38, completed in 0.0 seconds
len = 3
type = <class 'numpy.ndarray'>
array shape = (3, 4)


array([[10., 10., 20., 10.],
       [20., 20., 40., 20.],
       [30., 30., 60., 30.]], dtype=float32)

## case two

In [11]:
frame2 = calc_two(a, b, cube[0], cube[0], cube[0], c)
print('len = %s'%len(frame2))
print('type = %s'%type(frame2))
print('array shape =', np.array(frame2).shape)
frame2

len = 2
type = <class 'tuple'>
array shape = (2, 4)


(array([10., 10., 20., 10.], dtype=float32),
 array([-10., -10., -20., -10.], dtype=float32))

In [12]:
cube2 = calc_two(a, b, cube, cube, cube, c)
print('len = %s'%len(cube2))
print('type = %s'%type(cube2))
print('array shape =', np.array(cube2).shape)
cube2

len = 2
type = <class 'tuple'>
array shape = (2, 3, 4)


(array([[10., 10., 20., 10.],
        [20., 20., 40., 20.],
        [30., 30., 60., 30.]], dtype=float32), array([[-10., -10., -20., -10.],
        [-20., -20., -40., -20.],
        [-30., -30., -60., -30.]], dtype=float32))

In [13]:
mult2 = multiCPU(calc_two, multi_out=True, 
    posargs=[a,b], posvars=[cube,cube,cube], kwargs=dict(c=c))
print('len = %s'%len(mult2))
print('type = %s'%type(mult2))
print('array shape =', np.array(mult2).shape)
mult2

   2021-05-10 17:58:38, using 12 cores
   2021-05-10 17:58:38, completed in 0.17 seconds
len = 2
type = <class 'tuple'>
array shape = (2, 3, 4)


(array([[10., 10., 20., 10.],
        [20., 20., 40., 20.],
        [30., 30., 60., 30.]], dtype=float32), array([[-10., -10., -20., -10.],
        [-20., -20., -40., -20.],
        [-30., -30., -60., -30.]], dtype=float32))

In [14]:
mult2 = multiCPU(calc_two, multi_out=True, cpu_count=1,
    posargs=[a,b], posvars=[cube,cube,cube], kwargs=dict(c=c))
print('len = %s'%len(mult2))
print('type = %s'%type(mult2))
print('array shape =', np.array(mult2).shape)
mult2

   2021-05-10 17:58:38, using 1 core
   2021-05-10 17:58:38, completed in 0.0 seconds
len = 2
type = <class 'tuple'>
array shape = (2, 3, 4)


(array([[10., 10., 20., 10.],
        [20., 20., 40., 20.],
        [30., 30., 60., 30.]], dtype=float32), array([[-10., -10., -20., -10.],
        [-20., -20., -40., -20.],
        [-30., -30., -60., -30.]], dtype=float32))